#!/usr/bin/env bash
# A bash script that transfer files to my server

File_Path=$1
IP=$2
USER_NAME=$3
SSH_KEY=$4

if [ $# -lt 4 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    scp -o "StrictHostKeyChecking=no" -i "$SSH_KEY" "$File_Path" "$USER_NAME"@"$IP":~
fi
