#!/usr/bin/env bash
#install nginx and put hello world inside
# created a redirect page to a youtube link
# using sed to insert code intoa libe in the default file
# restart nginx and run crul

#redir="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "30i \\\t\tlocation /redirect_me {\n\t\t return 301 https://wwww.youtube.com/watch?v=QH2-TGUlwu4;\n\t\t}\n" /etc/nginx/sites-available/default
nginx -t
sudo service nginx restart
