#!/usr/bin/env bash
# README: redirect_me redirects to another page
#         replace a line with multiple lines using sed

sudo apt update && sudo apt install -y nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www/
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a \location /redirect_me { \ return 301 permanent "https://www.youtube.com/watch?v=QH2-TGUlwu4/"; \ }' /etc/nginx/sites-available/default
sudo service nginx restart
