#!/usr/bin/env bash
# README: redirect_me redirects to another page
#         replace a line with multiple lines using sed

sudo apt ugrade && sudo apt install -y nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www/
echo 'Hello World!' > /var/www/html/index
sudo sed -i 'listen 80 default_server/a \rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
