#!/usr/bin/env bash
#install nginx and put hello world inside
# using sed to insert code intoa libe in the default file
# restart nginx and run crul
# A default 404 err0r page

#redir="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

sudo apt-get update
sudo apt-get install nginx -y

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '/listen 80 default_server;/a \\terror_page 404 \/t404.html;\n\t\tlocation = \/404.html {\n\t\t\tinternal;\n\t\t\troot \/var\/www\/html;\n\t\t}' /etc/nginx/sites-available/default

nginx -t
sudo service nginx restart
