#!/usr/bin/env bash
# README: redirect_me redirects to another page
#         replace a line with multiple lines using sed

sudo apt update && sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www/
echo 'Hello World!' > /var/www/html/index.html
# a redirect to ayoutube page
sudo sed -i '/listen 80 default_server/a \location /redirect_me { \ return 301 permanent "https://www.youtube.com/watch?v=QH2-TGUlwu4/"; \ }' /etc/nginx/sites-available/default
# An error 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
sudo sed -i '/server {/a \ error_page 404 /error_404.html; \ location = /error_404.html { internal; \ } \ }' /etc/nginx/sites-available/default
service nginx start
