#!/usr/bin/env bash
# installing a new nginx in my server
# update packages qnd install an nginx software on the server

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo cp /etc/nginx/nginx.conf etc/nginx/nginx.conf_backup

# using sed text manipulative tol to serach for anywhere http is written and do insert the following code
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

sudo service nginx restart
