#!/usr/bin/env bash
# install and configure HAProxy on my server
# HAProxy (High Availability Proxy) is an open source load balancer proxy server that helps control
# incoming and outgoing traffic distrubuting it to different servers
# using an algrithim called roundrobin

# get all packages to lateest version
sudo apt-get -y update
sudo apt-get -y install software-properties-common


# add the HAProxy repo and install version 2.4
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get update
sudo apt-get install -y haproxy=2.4.\*

# HAProxy configuration and append to the haproxy.cfg file
balancer="
frontend haproxy_balancer
    \tbind*:80
    \tmode http
    \tdefault_backend webservers
  
backend webservers
    \tbalance roundrobin
    \tserver 257302-web-01 34.203.38.108:80 check
    \tserver 257302-web-02 52.205.94.188:80 check
"
# sudo cp -a /etc/haproxyy/haproxy.cfg{,.custom}
echo -e "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy start
