#!/usr/bin/env bash
# Scrip that ping an IP address as argument, displaying 5 times
# Prints err msg if no argument is passed

if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

ping -c 5 "$1"
