#!/usr/bin/env bash
# Creates a new var file and save the current PID in it
# echo msg for SIGTERM
# echo msg for SIGINT
# echo msg for SIGQUIT
# finally remove the file

sudo touch /var/run/myscript.pid
echo "$$" > /var/run/myscript.pid
#sudo chmod u+x /var/run/myscript.pid

    trap "echo 'I hate the kill command'; sudo rm /var/run/myscript.pid; exit" SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
   
    while true
    do
        echo 'To infinity and beyond'
        sleep 2
    done
