#!/usr/bin/env bash

# A bash script that prints hi after 9
count=1
msg="Best School"

while [ $count -lt 11 ]
do
	if [ $count -eq 10 ]
	then
		echo "Hi"
	fi

	echo "$msg"
    count=$((count + 1))
done
