#!/usr/bin/env bash
# checks gor file and print msgs


# checks if file exists
if [ -e "$file" ]; then

  echo "school file exists"

  # checks if file is empty
  if [ ! -s "$file" ]; then
    echo "school file is empty"
else
    echo "school file is not empty"
  fi

    # checks if file is a regular file
    if [ -f "$file" ]; then
      echo "school is a regular file"
  else
      echo "school is not a regular file"
    fi  
else
    echo "school file does not exist"
fi
