#!/usr/bin/env bash
# configuring a seever on ubuntu
# facebook.com resolves to 8.8.8.8
# localhost resolves to 127.0.0.1

cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8  facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts

#remove the newly created ip and resolve back to default IPs
rm ~/hosts.new
